# base.exp_name / model.type / model.ckpt_path 3개만 작성

base:
  save_path: /nas2/data/Janus_dataset/next/eval/ablation
  exp_name: 1107_argmax_chosen_wo_dense/ckpt_600
  task_name: dpgbench

  world_size: 4
  precision: bf16 


model:
  type: pl # * official / pl 
  model_path: /nas2/checkpoints/Janus-Pro-7B # deepseek-ai/Janus-Pro-1B
  cache_dir: /nas2/checkpoints/hf_cache_yj
  ckpt_path: /nas2/data/Janus_dataset/next/ckpt/ablation/1107_argmax_chosen_wo_dense/version_0/step=000600.ckpt
  attn_mode: flash_attention_2

task:
  batch_size: 8 # 4th 인 경우 32까지 괜찮고, 아닐 경우 8 로 설정
  # 고정
  num_workers: 4
  seed: [42]
  parallel_size: 1 
  temperature: 1
  cfg_weight: 5

  data_path: /home/rla020/research/bench/ELLA/dpg_bench/prompts
  # args 로 대체 (전체 1000)
  # s_idx:
  # e_idx: