# Step 2-2. Image Generation

seed_list: [0,1,2]
world_size: 2     # 4
# batch_size: 16  # attribute, layout
# batch_size: 12  # non-spatial
batch_size: 16    # complex
num_workers: 4

# data_path: /nas2/data/Janus_dataset/next_v2/iter2/prompt/step2/dense_prompt_0_8000.json
# data_path: /nas2/data/Janus_dataset/next_v2/iter2/prompt/step2/dense_prompt_8000_12000.json
data_path: /nas2/data/Janus_dataset/next_v2/iter2/prompt/step2/dense_prompt_12000_end.json
s_idx:
e_idx: 

save_path: /nas2/data/Janus_dataset/next_v2/iter2/images
save_name:

# iter1 ckpt
ckpt_path: /nas2/data/Janus_dataset/next/ckpt/1103_next_v2_use_soft_mask_argmax_chosen_v1_simpo_1_beta_5_sft_2_copo_0/version_0/step=000600.ckpt 
model:
  model_path: /nas2/checkpoints/Janus-Pro-7B 
  cache_dir: /nas2/checkpoints/hf_cache_yj 
  attn_mode: flash_attention_2 

generation_config: 
  parallel_size: 1
  temperature: 1.0
  cfg_weight: 5.0