# Step 1. Initial Prompt Generation

seed: 42
world_size: 1
batch_size: 1
num_workers: 4

save_path: /nas2/data/Janus_dataset/next_v2/janus_pro_1b/prompt/step1
save_name:

ckpt_path: 
model:
  # model_path: /nas2/checkpoints/Janus-Pro-7B #
  model_path: deepseek-ai/Janus-Pro-1B
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2

max_len:          # total length
repeat: 8         # default
interval: 100     # few-shot example replacement interval
category:         # options: color1, color2, texture1, texture2, shape1, shape2, 2D_spatial, 3D_spatial, numeracy1, numeracy2, non-spatial, complex

generation_config:
  do_sample: True
  temperature: 1.0
  max_new_tokens: 512