# Step 3-1. Compositional VQA

seed: 42
world_size: 1
batch_size: 32 # attribute, layout
# batch_size: 4 # non-spatial
# batch_size: 8 # complex
num_workers: 4

# vqa question prompt
data_path: /nas2/data/Janus_dataset/next_v2/ablation/wo_dense/vqa_question_added_978.json
s_idx: 
e_idx: 

img_constraint: 3
image_path: /nas2/data/Janus_dataset/main_exp/aaai/janus/images_short_prompt
save_path: /nas2/data/Janus_dataset/next_v2/ablation/wo_dense
save_name: vqa_result_added


ckpt_path: 
model:
  model_path: /nas2/checkpoints/Janus-Pro-7B # deepseek-ai/Janus-Pro-1B
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2
  # flash_attn: True

generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 256